name: vuz_app
description: "A new Flutter project."

publish_to: 'none' 

version: 0.3.3+21

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  # твои текущие зависимости (оставь как есть)
  flutter_inappwebview: ^6.0.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2

  # пуши
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  
  html: ^0.15.4

  package_info_plus: ^8.0.0

  share_plus: ^10.0.0
  http: ^1.2.2

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/splash/logo_big.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FF8C00"
  adaptive_icon_foreground: "assets/icon/icon.png"
